version: '3'

services:
  data-dispatcher:
    image: data-dispatcher:beta-0.1.0
    build:
      context: ./data_dispatcher-service
      dockerfile: Dockerfile.data
    ports:
      - "9001:9001"
    volumes:
      - ./data_dispatcher-service:/data-app
    networks:
      - iot-platform

  device-manager:
    image: device-manager:beta-0.1.0
    build:
      context: ./device-service
      dockerfile: Dockerfile.device
    ports:
      - "9010:9010"
    volumes:
      - ./device-service:/device-app
    networks:
      - iot-platform
    # ... (your Flask app 2 configuration)

  kafka-dispatcher:
    image: kafka-service:beta-0.1.0
    build:
      context: ./kafka-service
      dockerfile: Dockerfile.device
    ports:
      - "9002:9002"
    volumes:
      - ./device-service:/device-app
    networks:
      - iot-platform
    # ... (your Flask app 2 configuration)

networks:
  iot-platform:
    driver: bridge