version: '3'

services:
  data-dispatcher:
    image: data-dispatcher:beta-0.0.1
    build:
      context: data_dispatcher-service
      dockerfile: Dockerfile.data
    ports:
      - "9001:9001"
    volumes:
      - ./data_dispatcher-service:/data-app
    networks:
      - iot-platform

  device-manager:
    image: device-manager:beta-0.0.1
    build:
      context: ./device-service
      dockerfile: Dockerfile.device
    ports:
      - "9010:9010"
    volumes:
      - ./device-service:/device-app
    networks:
      - iot-platform
    # ... (your Flask app 2 configuration)

  supervisor:
    image: supervisor:beta-0.0.1
    build:
      context: ./supervisor-service
      dockerfile: Dockerfile.supervisor
    ports:
      - "9003:9003"
    volumes:
      - ./supervisor-service:/supervisor-app
    networks:
      - iot-platform
    # ... (your Flask app 3 configuration)

  nginx:
    image: nginx
    ports:
      - "80:80"    # Redirect HTTP to HTTPS
#      - "443:443"  # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - /path/to/certs:/etc/nginx/certs:ro   # Mount SSL certificate folder
    networks:
      - iot-platform

networks:
  iot-platform:
    driver: bridge