pidfile = 'supervisor.pid'
worker_tmp_dir = '/dev/shm'
worker_class = 'gthread'
# worker_class = 'gevent'
workers = 1
worker_connections = 1000
timeout = 30
keepalive = 2
threads = 2
proc_name = 'supervisor'
bind = '0.0.0.0:9003'
backlog = 2048
accesslog = '-'
errorlog = '-'