FROM python:3.11
COPY requirements.txt /device-app/requirements.txt
WORKDIR /device-app
RUN pip install -r requirements.txt
COPY . /device-app
CMD ["gunicorn", "-c", "guni_config.py", "run:app"]
EXPOSE 9002