FROM python:3.10
COPY requirements.txt /device-service/requirements.txt
WORKDIR /device-service
RUN pip install -r requirements.txt
COPY . /device-service
CMD ["nohup", "gunicorn", "-c", "guni_config.py", "run:app", "&"]
EXPOSE 9010