FROM python:3.11
COPY requirements.txt /data-app/requirements.txt
WORKDIR /data-app
RUN pip install -r requirements.txt
COPY . /data-app
CMD ["nohup", "gunicorn", "-c", "guni_config.py", "run:app", "&"]
EXPOSE 9001